### ISSUE TITLE
Touch issue with GTK+3 applications in Rootston

### ISSUE THREAD

**Issue by Kareema0** [swaywm/wlroots#1453] opened 2019-01-06 17:56 UTC
### For at least some touch devices, touch input doesn't work as expected with GTK+3 applications when using Rootston.

The same applications are running as expected in Weston.

**Observed behaviour** (Rootston): For GTK+3 UI elements (tested with Gtk.Button), there are signals emitted to the wrong GTK UI object and some expected signals missing at all.

**Test application**: The issue has been tested with a small GTK+3 app written in Vala: [buttonbox.vala](https://pastebin.com/26tfiNVf). The app has 3 GTK buttons, each connected to the following signals: clicked, pressed, released, enter, leave. 

**Test case**: 
Tapping button 1, button 2, button 2, button1 in this order. Tested with Rootston and Weston with WAYLAND_DEBUG=client. Logs with the signals emitted in each case are attached.

**Test configuration**:
- Golden Delicious GTA04 board, TSC2007 touchscreen, kernel 4.19.12-letux+ armv7l, Debian Buster, GTK+ 3.24.2-3
- Raspberry Pi 3B+, ADS7846 touchscreen, kernel 4.14.86-v8-rpi aarch64, PureOS, GTK+ 3.24.2-3 (only short test without logs so far)

**Notes**: 
- This problem doesn't seem to be present in all environments with touchscreens.
- Trying wlroots touch demo doesn't show any unexpected behaviour
- No problems with touch using X11 as well

**Logs**:
[rootston-buttonbox-debug-log.txt](https://github.com/swaywm/wlroots/files/2730712/rootston-buttonbox-debug-log.txt)
[weston-buttonbox-debug-log.txt](https://github.com/swaywm/wlroots/files/2730713/weston-buttonbox-debug-log.txt)

**Source code**:
[buttonbox.vala](https://pastebin.com/26tfiNVf)

**Comment by agx** [comment] 2019-01-07 07:36
@Kareema0 if you already have a test application it might make sense to link it here (with build instruction) so it's easy to reproduce.

**Comment by Kareema0** [comment] 2019-01-07 18:15
@agx Good idea - updated the issue with a link to the [source code](https://pastebin.com/26tfiNVf). Can be run with
`vala --pkg=gtk+-3.0 buttonbox.vala`

**Comment by dano6** [comment] 2019-01-08 16:18
I can see similar issue with gnome documents, scrolling of the document works, but none of the buttons react to touch input. And I have still issue with this: https://github.com/swaywm/sway/issues/2299#issuecomment-430705891

**Comment by dos1** [comment] 2019-08-17 16:37
Is it maybe fixed by https://github.com/swaywm/wlroots/commit/4f4d3cf2a25f7af022e51b861ef04f7c4a94b768?

**Comment by emersion** [comment] 2020-06-04 08:46
Closing because this is a rootston bug. rootston ahs been removed from the wlroots tree.

**Closed by emersion** 2020-06-04 08:46 UTC
Labels: bug
