### ISSUE TITLE
Unable to add DRM framebuffer with new wlroots 

### ISSUE THREAD

**Issue by SonTuong** [swaywm/wlroots#2919] opened 2021-05-09 15:35 UTC
I have used wlroots version 0.11.0 until now. Today I decided to update wlroots, tested with tinywl and nothing showed up on screen. I switched back to version 0.11.0 and it worked again. I also tested with 0.12.0 and it worked. I'm using Pinephone. Here is the log:

> 00:00:00.000 [ERROR] [libseat] [libseat/backend/seatd.c:78] Could not connect to socket /run/seatd.sock: No such file or directory
00:00:00.000 [INFO] [libseat] [libseat/libseat.c:70] Backend 'seatd' failed to open seat, skipping
00:00:00.051 [INFO] [libseat] [libseat/libseat.c:67] Seat opened with backend 'logind'
00:00:00.052 [INFO] [backend/session/session.c:110] Successfully loaded libseat session
00:00:00.074 [INFO] [backend/backend.c:175] Found 1 GPUs
00:00:00.075 [INFO] [backend/drm/backend.c:182] Initializing DRM backend for /dev/dri/card0 (sun4i-drm)
00:00:00.075 [DEBUG] [backend/drm/drm.c:68] Using atomic DRM interface
00:00:00.075 [DEBUG] [backend/drm/drm.c:81] ADDFB2 modifiers unsupported
00:00:00.075 [INFO] [backend/drm/drm.c:243] Found 2 DRM CRTCs
00:00:00.075 [INFO] [backend/drm/drm.c:170] Found 6 DRM planes
00:00:00.331 [INFO] [render/egl.c:305] Using EGL 1.4
00:00:00.331 [INFO] [render/egl.c:306] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
00:00:00.331 [INFO] [render/egl.c:307] Supported EGL display extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_partial_update EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display 
00:00:00.331 [INFO] [render/egl.c:309] Supported EGL device extensions: EGL_EXT_device_drm
00:00:00.331 [INFO] [render/egl.c:311] EGL vendor: Mesa Project
00:00:00.331 [DEBUG] [render/egl.c:149] Supported DMA-BUF formats: AB4H AR24 AB24 XR24 XB24 AR15 RG16 R8   GR88 YUV9 YU11 YU12 YU16 YU24 YVU9 YV11 YV12 YV16 YV24 NV12 NV16 AYUV XYUV YUYV UYVY 
00:00:00.331 [DEBUG] [render/egl.c:150] EGL DMA-BUF format modifiers supported
00:00:00.341 [INFO] [render/gles2/renderer.c:784] Creating GLES2 renderer
00:00:00.342 [INFO] [render/gles2/renderer.c:785] Using OpenGL ES 2.0 Mesa 21.0.3
00:00:00.342 [INFO] [render/gles2/renderer.c:786] GL vendor: lima
00:00:00.342 [INFO] [render/gles2/renderer.c:787] GL renderer: Mali400
00:00:00.342 [INFO] [render/gles2/renderer.c:788] Supported GLES2 extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_depth_texture GL_OES_packed_depth_stencil GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_pack_reverse_row_order GL_EXT_occlusion_query_boolean GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_separate_shader_objects GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_draw_elements_base_vertex GL_EXT_texture_border_clamp GL_KHR_context_flush_control GL_OES_draw_elements_base_vertex GL_OES_texture_border_clamp GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_KHR_parallel_shader_compile 
00:00:00.387 [DEBUG] [render/allocator.c:30] Trying to create gbm allocator
00:00:00.405 [DEBUG] [render/gbm_allocator.c:192] Created GBM allocator with backend drm
00:00:00.406 [DEBUG] [render/gbm_allocator.c:195] Using DRM node /dev/dri/card0
00:00:00.491 [DEBUG] [xcursor/wlr_xcursor.c:243] Loaded cursor theme 'default' at size 24 (123 available cursors)
00:00:00.491 [DEBUG] [backend/libinput/backend.c:87] Initializing libinput
00:00:00.601 [DEBUG] [backend/libinput/events.c:94] Added 1c21800.lradc [1:1]
00:00:00.632 [DEBUG] [backend/libinput/events.c:94] Added Goodix Capacitive TouchScreen [1046:4097]
00:00:00.654 [DEBUG] [backend/libinput/events.c:94] Added axp20x-pek [0:0]
00:00:00.676 [DEBUG] [backend/libinput/events.c:94] Added PinePhone Headset Jack [0:0]
00:00:00.699 [DEBUG] [backend/libinput/backend.c:133] libinput successfully initialized
00:00:00.699 [INFO] [backend/drm/drm.c:1257] Scanning DRM connectors on /dev/dri/card0
00:00:00.699 [INFO] [backend/drm/drm.c:1315] Found connector 'DSI-1'
00:00:00.699 [INFO] [backend/drm/drm.c:1351] 'DSI-1' connected
00:00:00.699 [DEBUG] [backend/drm/drm.c:1352] Current CRTC: 41
00:00:00.699 [INFO] [backend/drm/drm.c:1363] Physical size: 68x136
00:00:00.699 [INFO] [backend/drm/drm.c:1394] Detected modes:
00:00:00.699 [INFO] [backend/drm/drm.c:1416]   720x1440@60006 (preferred)
00:00:00.699 [INFO] [backend/drm/drm.c:1315] Found connector 'HDMI-A-1'
00:00:00.699 [DEBUG] [backend/drm/drm.c:1111] Reallocating CRTCs
00:00:00.699 [DEBUG] [backend/drm/drm.c:1122] State before reallocation:
00:00:00.699 [DEBUG] [backend/drm/drm.c:1128]   'DSI-1' crtc=0 state=1 desired_enabled=1
00:00:00.699 [DEBUG] [backend/drm/drm.c:1128]   'HDMI-A-1' crtc=-1 state=0 desired_enabled=0
00:00:00.699 [DEBUG] [backend/drm/drm.c:1179] State after reallocation:
00:00:00.699 [DEBUG] [backend/drm/drm.c:1186]   'DSI-1' crtc=0 state=1 desired_enabled=1
00:00:00.699 [DEBUG] [backend/drm/drm.c:1186]   'HDMI-A-1' crtc=-1 state=0 desired_enabled=0
00:00:00.699 [INFO] [backend/drm/drm.c:1468] connector DSI-1: Requesting modeset
00:00:00.700 [INFO] [backend/drm/drm.c:772] connector DSI-1: Modesetting with '720x1440@60006mHz'
00:00:00.700 [DEBUG] [backend/drm/drm.c:656] connector DSI-1: Initializing renderer
00:00:00.700 [DEBUG] [render/swapchain.c:105] Allocating new swapchain buffer
00:00:00.702 [DEBUG] [render/gbm_allocator.c:123] Allocated 720x1440 GBM buffer (format 0x34325241, modifier 0xFFFFFFFFFFFFFF)
00:00:00.703 [DEBUG] [render/gles2/renderer.c:133] Created GL FBO for buffer 720x1440
00:00:00.709 [DEBUG] [backend/drm/util.c:209] drmModeAddFB2 failed (No such file or directory), falling back to legacy drmModeAddFB
00:00:00.710 [ERROR] [backend/drm/util.c:218] Unable to add DRM framebuffer: No such file or directory
00:00:00.710 [DEBUG] [backend/drm/renderer.c:411] Failed to import GBM BO in KMS
00:00:00.710 [ERROR] [backend/drm/renderer.c:317] Failed to import buffer
00:00:00.710 [ERROR] [backend/drm/drm.c:677] connector DSI-1: Failed to initialize renderer:initial page-flip failed
00:00:00.710 [ERROR] [backend/drm/drm.c:777] connector DSI-1: Failed to initialize renderer for plane
00:00:00.710 [DEBUG] [backend/drm/drm.c:713] connector DSI-1: Output has a desired mode and a CRTC, attempting a modeset
00:00:00.710 [INFO] [backend/drm/drm.c:772] connector DSI-1: Modesetting with '720x1440@60006mHz'
00:00:00.710 [DEBUG] [backend/drm/drm.c:656] connector DSI-1: Initializing renderer
00:00:00.710 [DEBUG] [render/swapchain.c:105] Allocating new swapchain buffer
00:00:00.713 [DEBUG] [render/gbm_allocator.c:123] Allocated 720x1440 GBM buffer (format 0x34325241, modifier 0xFFFFFFFFFFFFFF)
00:00:00.713 [DEBUG] [render/gles2/renderer.c:133] Created GL FBO for buffer 720x1440
00:00:00.716 [DEBUG] [backend/drm/util.c:209] drmModeAddFB2 failed (No such file or directory), falling back to legacy drmModeAddFB
00:00:00.717 [ERROR] [backend/drm/util.c:218] Unable to add DRM framebuffer: No such file or directory
00:00:00.717 [DEBUG] [backend/drm/renderer.c:411] Failed to import GBM BO in KMS
00:00:00.717 [ERROR] [backend/drm/renderer.c:317] Failed to import buffer
00:00:00.717 [ERROR] [backend/drm/drm.c:677] connector DSI-1: Failed to initialize renderer:initial page-flip failed
00:00:00.717 [ERROR] [backend/drm/drm.c:777] connector DSI-1: Failed to initialize renderer for plane

**Comment by emersion** [comment] 2021-05-10 07:57
Duplicate of https://github.com/swaywm/wlroots/issues/2795

**Closed by emersion** 2021-05-10 07:57 UTC
