### ISSUE TITLE
rootston `close` command should work on popups/etc

### ISSUE THREAD

**Issue by martinetd** [swaywm/wlroots#543] opened 2017-12-30 09:45 UTC
The `close` rootston command doesn't work on (at least some) xdg shell popups

Reproducer:
open gnome-terminal, then a popup within (e.g. `File` menu); press close key, nothing happens.
Same with gnome-calculator and any of the drop-downs.

I thought this would be easy because rootston's xdg_shell_v6.c's close() only does something for toplevel... But it looks like we're actually considering some toplevel surface at this point.
Starting e.g. gnome-calculator with `WAYLAND_DEBUG=1` I see the same `zxdg_toplevel_v6@27.close()` trace (same window id) whether I try to close with a popup open (nothing happens) or when I do without (window actually closes)...
So I think this is rather closer to an enhancement e.g. "close should force kill underneath shell if the nice request was ignored" ?
Could also be "close should try to terminate the popup and not the toplevel window if a popup is focused", which might or might not work better, but there's no similar `send_close` function for popups in the xdg shell interface, so I have no idea how we'd do that cleanly.

**Comment by emersion** [comment] 2017-12-30 10:06
The fix might be as simple as calling `wlr_seat_pointer_end_grab` and `wlr_seat_keyboard_end_grab`. Though I'm not sure if we always want to end grabs when closing a view, because the grab might not belong to the client being closed. Maybe an additional check on the grab would do it.

**Comment by SirCmpwn** [comment] 2017-12-30 15:39
Should it? I'm not sure it should.

**Comment by martinetd** [comment] 2017-12-30 15:55
Hmm, well, I had never tried in X11 and it looks like that prevents wmii's "close" command to work as well, but from a user experience point of view I think it should work, or at least end grab? What makes the popup so great that it'd make the underlying window immortal?
Ultimately I don't care much (given I never had to kill a window with a popup before apparently!), it just felt odd when I went on a spree killing just about everything and taking bets to see if rootston would crash :p (sadly it didn't as much as I had hoped, the devs are no fun)

**Comment by acrisci** [comment] 2018-01-03 11:48
Can reproduce. This is definitely a bug.

**Comment by acrisci** [comment] 2018-03-24 19:25
Maybe not so much of a bug as I thought. We are sending the toplevel close message, but gtk is ignoring us. But I don't like this behavior and I want rootston to close it anyway. So the approach I've taken is to close all the popups first and then close.

**Closed** 2018-03-24 21:02 UTC
Labels: bug
