### ISSUE TITLE
Computer freeze while using rootston and closing it via kill in tty

### ISSUE THREAD

**Issue by epsilon-0** [swaywm/wlroots#1583] opened 2019-02-27 15:22 UTC
This is a bug when using rootston and is affecting some other compositors built on top of wlroots.
It seems to be affecting those who are not using elogind/systemd in their OS and are using the suid method for using wlroots. When you start rootston via tty1 and then go kill it in tty2 the computer freezes.

Arch: Gentoo linux (Kernel 4.20.6)
Reproducing the bug: 
- Install wlroots with rootston (without elogind/systemd installed)
- Start rootston from tty
- Go to another tty and kill the process of rootston

Expected behavior: rootston dies without lamentations
Bug: Computer freezes. Can't switch to different tty. Have to reboot via hard reset.

---- Notes (maybe helpful)
Seems like when you use `secure_getenv("HOME")` the result is `null` if you have suid set on the executable.

**Comment by epsilon-0** [comment] 2019-02-27 15:22
Maybe related bug #1481

**Comment by emersion** [comment] 2019-02-27 15:27
Duplicate of #1481

**Closed by emersion** 2019-02-27 15:27 UTC
