### ISSUE TITLE
XWayland not working

### ISSUE THREAD

**Issue by jgmdev** [swaywm/wlroots#2223] opened 2020-05-25 19:14 UTC
I'm trying to run sway or any other wlroots based compositor like wayfire under aarch64 in the Odroid N2 single board computer which has a Mali GPU. The wayland part works perfectly, sway opens, renders top panel and wallpaper. But, if I try to launch a X application (like pressing Super + d for dmenu), causes sway to completely exit. 

Just in case in weston and gnome XWayland works correctly. Attached the generated log with sway -d -V 2> sway.log

[sway.log](https://github.com/swaywm/wlroots/files/4678573/sway.log)

**Comment by Xyene** [comment] 2020-05-25 19:28
From this part of the log:

```
...
00:00:00.044 [INFO] [render/gles2/renderer.c:584] GL renderer: Mali-G52
...
00:00:04.328 [INFO] [xwayland/server.c:92] WAYLAND_SOCKET=26 Xwayland :1 -rootless -terminate -listen 23 -listen 25 -wm 48
glamor: No eglstream capable devices found
glamor: 'wl_drm' not supported
Missing Wayland requirements for glamor GBM backend
Missing Wayland requirements for glamor EGLStream backend
Failed to initialize glamor, falling back to sw
00:00:04.523 [DEBUG] [types/wlr_surface.c:615] New wlr_surface 0xaaab02e58280 (res 0xaaab03291880)
00:00:04.524 [DEBUG] [xwayland/server.c:333] sent SIGUSR1 to process 3877
(EE)00:00:03.772  [common/ipc-client.c:88] Unable to receive IPC responsefailed to read Wayland events: Connection reset by peer

cannot open display
```

This sounds like a duplicate of https://github.com/swaywm/wlroots/pull/1815.

**Comment by emersion** [comment] 2020-05-25 19:29
Are you sure sway doesn't segfault? Check with `coredumpctl -r`.

**Comment by jgmdev** [comment] 2020-05-25 19:52
> Are you sure sway doesn't segfault? Check with `coredumpctl -r`.

`coredumpctl -r | grep sway` doesn't displays anything for sway.

**Comment by emersion** [comment] 2020-05-25 19:55
Ah, is this a driver dying because of SIGUSR1 again?

**Comment by emersion** [comment] 2020-05-25 19:56
Related https://github.com/swaywm/wlroots/issues/2154

**Comment by emersion** [comment] 2020-05-27 07:25
Actually, you seem to be using a proprietary GPU driver. Since we can't read the source code, we won't be able to understand what's going on and send them a patch.

**Closed by emersion** 2020-05-27 07:25 UTC

**Comment by jgmdev** [comment] 2020-05-28 03:15
I patched wl-roots as shown on #1815 and that fixed the issue, could you guys please implement a solution based on the proposal at #2154. I know companies like ARM are been kind of unfair on releasing only closed source user space drivers which leaves us with this mess, but for those (many) of us that can't find other alternatives is kind of sad to not be able to run such useful software (wl-roots + compositors) because of a small bug on how a signal is emitted. The binary driver implements GBM which is the requirement of Sway, so the situation is not the same as Nvidia where they want to only support a whole different methodology.

While panfrost matures... many that use these boards will be stuck with what ARM, Amlogic (insert other arm vendor here) releases :(

**Comment by emersion** [comment] 2020-05-28 06:57
>could you guys please implement a solution based on the proposal at #2154

Could you send a patch doing this?

**Comment by jgmdev** [comment] 2020-05-28 17:04
> Could you send a patch doing this? 

I'm not familiar with the codebase and the ipc programming methodology but I will see if I can do something after studying parts of the code base next week. Some guidance would be appreciated.

**Comment by emersion** [comment] 2020-05-28 17:46
Sure, feel free to come discuss on IRC in #sway-devel on Freenode and ask questions :)
