### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/wlroots#2242] opened 2020-06-01 20:00 UTC
Of late, I'm seeing frequent crashes when clicking on / browsing menus. Not sure if this is related to PR#2217. Trace attached.

```
sway version 1.4-613abdda (Jun  1 2020, branch 'master')
```

[gdb.txt](https://github.com/swaywm/wlroots/files/4713173/gdb.txt)

**Comment by Xyene** [comment] 2020-06-01 20:04
This is a duplicate of https://github.com/swaywm/sway/issues/5294; there are pending PRs https://github.com/swaywm/wlroots/pull/2217 and https://github.com/swaywm/sway/pull/5368 to fix it. You can also locally revert https://github.com/swaywm/sway/commit/091f580b7cb0df92f0f6e0be34b52f8abfdbe97a, which introduced the issue.

**Closed by Xyene** 2020-06-01 20:04 UTC
