### ISSUE TITLE
Add support for `wp_viewporter`

### ISSUE THREAD

**Issue by 1ace** [swaywm/wlroots#2218] opened 2020-05-22 21:16 UTC
I know this is a big one that will potentially require a lot of refactoring and work in wlroots, but since Firefox is planning on making use of it to reduce power consumption it would be nice to have it on Sway, eventually :smiley:

- [wp_viewporter spec](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/stable/viewporter/viewporter.xml)
- [Firefox task tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1617498)

/cc @ascent12, this seems in your wheelhouse

**Comment by emersion** [comment] 2020-05-22 21:17
Yup!

Duplicate of https://github.com/swaywm/wlroots/issues/633

Early WIP patch: https://github.com/swaywm/wlroots/pull/2092

**Closed by emersion** 2020-05-22 21:17 UTC

**Comment by 1ace** [comment] 2020-05-22 21:21
Ah my bad, I searched but obviously not properly :upside_down_face: 

Thanks for the link, and for the work!
