### ISSUE TITLE
Popups in Gedit crash the whole app or the compositor

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#888] opened 2018-04-23 10:32 UTC
This happened at commit https://github.com/swaywm/wlroots/pull/885/commits/fa84b267e0fdc3bcdd43dc2d06b55ffad03059a3

Steps to reproduce: Start rootston, start gedit, move cursor over the "Open" menu. A popup should open, but instead gedit crashes, or sometimes rootston. Doesn't happen before this commit. I'm still investigating what exactly is going on.

**Comment by emersion** [comment] 2018-04-23 10:37
I think #1842 is a duplicate of this one.

**Comment by ammen99** [comment] 2018-04-23 10:44
Seems like the same bug, as it happens with other Gtk apps as well.

**Closed** 2018-04-24 08:01 UTC
Labels: bug
