### ISSUE TITLE
udev dependency should be optional

### ISSUE THREAD

**Issue by DemiMarie** [swaywm/wlroots#3225] opened 2021-09-28 16:20 UTC
udev is very much Linux-specific, and makes no sense on non-Linux platforms.  See https://www.sizeofvoid.org/posts/2021-09-26-openbsd-wayland-report/ for one example.

**Comment by emersion** [comment] 2021-09-28 16:23
Duplicate of https://github.com/swaywm/wlroots/issues/2257.

**Closed by emersion** 2021-09-28 16:23 UTC
