### ISSUE TITLE
Context menus wrong position on multiple displays with mixed DPI

### ISSUE THREAD

**Issue by HoshiYamazaki** [swaywm/wlroots#1678] opened 2019-04-27 20:09 UTC
Tested on Terminator and Firefox, the same bug occurs in Gnome so I don't know where it happens, I heard that it's libgtk bug but probably not. I use Wayland build of Firefox of course, and scale 1.75 or 2 of my secondary 4K monitor.

If there is similar issue - sorry for posting it.

**Comment by HoshiYamazaki** [comment] 2019-04-27 20:20
Also, in sway opening context menu near border causes bug where border is at higher index than context window, and that causes graphical defect.

See here:
https://imgur.com/a/pPg0vQA

**Comment by ammen99** [comment] 2019-04-27 21:05
Just a tip, on most wlroots-based compositors (including Sway) you can use https://github.com/emersion/grim to create screenshots.

**Comment by HoshiYamazaki** [comment] 2019-04-28 04:49
> Just a tip, on most wlroots-based compositors (including Sway) you can use https://github.com/emersion/grim to create screenshots.

Yes I know but I had not hotkey attached and doing it via terminal was causing context menu dissapear so I though it will be faster to do with phone.

**Comment by RedSoxFan** [comment] 2019-04-30 03:40
> Tested on Terminator and Firefox, the same bug occurs in Gnome so I don't know where it happens, I heard that it's libgtk bug but probably not. I use Wayland build of Firefox of course, and scale 1.75 or 2 of my secondary 4K monitor.

I'm pretty sure this is related to https://github.com/swaywm/sway/issues/3135#issuecomment-448794177. 

For Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1423598. It looks like that was fixed within the past week and should be included in the recent nightly builds. 

I'm not sure what the status is for Terminator.

> Also, in sway opening context menu near border causes bug where border is at higher index than context window, and that causes graphical defect.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1528021, which was closed as a duplicate of the issue above and thus should also be resolved in recent nightly builds.

**Closed by RedSoxFan** 2019-04-30 03:40 UTC
