### ISSUE TITLE
Pasting in Emacs causes wlroots to run out of pipes

### ISSUE THREAD

**Issue by mssdvd** [swaywm/wlroots#2192] opened 2020-05-11 15:06 UTC
* Step to reproduce
1) Open emacs
2) Paste some text from the primary clipboard
4) Emacs and any other GUI application crash
After that I can't open any applications but sway still works.

When I use my usual config the first thing to crash is redshift and after a few seconds every window crash. 

* Sway Version:
sway version 1.4-a8a6ed66 (May 11 2020, branch 'master')

* Debug Log:
https://gist.github.com/mssdvd/d00ef14c7df092dfed9c582abd8aedc0

* Configuration File:
````
bindsym Mod4+c exec clipman pick -t rofi
exec wl-paste -t text --watch clipman store
include /etc/sway/config
include /etc/sway/config.d/*
````
* Stack Trace:
None because Sway didn't crash

**Comment by emersion** [comment] 2020-10-12 08:54
Can you try wlroots master and see if this is fixed by https://github.com/swaywm/wlroots/pull/2428?

**Comment by mssdvd** [comment] 2020-10-12 09:43
I tried it and the system freezed (reboot required). I'll make a more detailed
report later.

**Comment by mssdvd** [comment] 2020-10-13 16:27
I'm having difficulty producing a decent size log. The only time that the system has behaved badly the log was about 140MB. That time the system behaved like I described before. All other times the system did not respond to inputs.

**Comment by emersion** [comment] 2020-10-13 16:28
Consider using SSH to investigate the frozen machine.

**Comment by Xyene** [comment] 2021-02-08 02:04
Could you try wlroots master again? A lot of Xwayland clipboard fixes went in a few days ago, and I think this may have been fixed.

**Comment by mssdvd** [comment] 2021-02-08 12:09
Unfortunately it keeps crashing. 

Log: https://gist.github.com/mssdvd/7ebf06bb55885d61f45fc13c5b5f6faf

**Comment by Xyene** [comment] 2021-02-08 18:00
Thanks for testing. It's now failing in a different way than before. In your first log, the requestor window was the same in each attempt; here, Emacs is creating a new window for each attempt. This sounds like an Emacs bug... https://github.com/swaywm/wlroots/issues/2326 would prevent the fd exhaustion, but not fix Emac's behavior here.

Some questions to try to get to the bottom of this:

* What version of Emacs are you running?
* Is running `wl-paste` still a requirement in reproducing?
* Does the issue reproduce with `wl-paste`/`clipman` master?
* Does the issue reproduce if the primary selection owner is another X11 window?
* Does the issue reproduce if the primary selection owner is a Wayland window?
* In the last two cases, what is the output of `xclip -selection primary -o -t TARGETS`? `xclip -selection clipboard -o -t TARGETS`?

**Comment by mssdvd** [comment] 2021-02-08 23:32
- 27.1
- I never experienced it without `wl-paste` running
- I have not tried them but the unreleased commits do not seem to change anything 
- I haven't tried it (I'll update soon)
- Yes, Firefox in this case

### xclip -selection primary -o -t TARGETS

```
TIMESTAMP
MULTIPLE
TEXT
COMPOUND_TEXT
STRING
UTF8_STRING
TARGETS
LENGTH
DELETE
FILE_NAME
CHARACTER_POSITION
LINE_NUMBER
COLUMN_NUMBER
OWNER_OS
HOST_NAME
USER
CLASS
NAME
ATOM
INTEGER
SAVE_TARGETS
```

### xclip -selection clipboard -o -t TARGETS

```
TIMESTAMP
MULTIPLE
TEXT
COMPOUND_TEXT
STRING
UTF8_STRING
TARGETS
LENGTH
DELETE
FILE_NAME
CHARACTER_POSITION
LINE_NUMBER
COLUMN_NUMBER
OWNER_OS
HOST_NAME
USER
CLASS
NAME
ATOM
INTEGER
SAVE_TARGETS
```

**Comment by Xyene** [comment] 2021-02-10 06:48
Hmm, I really can't reproduce this... How do the below versions compare to yours?

* emacs-gtk
```
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0)
 of 2020-11-07, modified by Debian
```
* Firefox 86.0b8
* wl-clipboard 2.0.0
* clipman 1.5.2

**Comment by mssdvd** [comment] 2021-02-10 07:39
* emacs
```
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28 
```
* Firefox 85.01
* wl-clipboard 2.0.0
* clipman 1.5.2

**Comment by mssdvd** [comment] 2021-02-10 07:50
I tried again to reproduce it:  https://gist.github.com/mssdvd/ba6a56e0b3520fb5bfc0db8ba75561ca

This time gammastep and emacs crashed and the system didn't freeze.

**Comment by Xyene** [comment] 2021-02-10 08:04
Dumb question: does the issue reproduce if you start emacs via `emacs` rather than `emacsclient`? My `emacsclient` is hanging during startup, and right now that's all I can think of that's different (I just tried Firefox 85.01, and I *hope* GTK 3.24.22 isn't hugely different from 3.24.23).

**Comment by mssdvd** [comment] 2021-02-10 10:00
Yes, the issue is still there.

I'm testing it with this config:
```
# the standard config
include /etc/sway/config

exec {
    wl-paste -t text --watch clipman store
    echo "blaksdlsdkasdfdkjfhkajdfhjakdhfjkasdhfjasdbhjbrhasgfhdghfhjfhsdaj"|wl-copy
    emacs -Q 
}
```
* Step to reproduce
1. Yank the string many times with `C-y`
2. Click on any point of the buffer with the mouse 
3.  Kill (cut) the line  with `C-w`
4. Repeat 2 and 3 until a crash

These are pretty vague steps but they often lead to the crash of Emacs and XWayland however I'haven't been able to find a precise sequence yet. 

Now I'm working on an elisp script that hopefully will automates the process and I will try some other XWayland editor.

**Comment by Xyene** [comment] 2021-02-10 15:05
OK, I understand now, and have been able to reproduce based on your last message.

> 2. Paste some text from the primary clipboard

This was misleading :)

I assumed you were talking about https://www.gnu.org/software/emacs/manual/html_node/emacs/Primary-Selection.html

However, `C-y` etc. paste from the _clipboard_: https://www.gnu.org/software/emacs/manual/html_node/emacs/Clipboard.html#Clipboard

These are different selections, and the issue doesn't repro with the primary selection, only with the clipboard.

**Comment by mssdvd** [comment] 2021-02-10 15:26
Oh, sorry to have confused you! 

However the initial report is correct, the problem occurred when using the primary selection because it is probably the one I use most often between emacs and other applications.

Does the work done on XWayland in the last days only concern the primary selection or also the clipboard selection?

**Comment by Xyene** [comment] 2021-02-10 15:32
No problem, happy we got to the bottom of things. I imagine things would have reproduced with the primary selection if `wl-paste` was running on the primary selection rather than the clipboard.

The work was for both primary and clipboard selections, but X11 is hard and it's easy to muck up.

Anyway, the badness are these lines:

```
00:00:17.110 [DEBUG] [wlr] [xwayland/selection/incoming.c:486] XCB_XFIXES_SELECTION_NOTIFY (selection=275, owner=4194627)
00:00:17.111 [DEBUG] [wlr] [xwayland/selection/incoming.c:486] XCB_XFIXES_SELECTION_NOTIFY (selection=275, owner=2097153)
00:00:17.111 [DEBUG] [wlr] [xwayland/selection/outgoing.c:375] XCB_SELECTION_REQUEST (time=471206 owner=2097153, requestor=2097153 selection=275, target=277, property=276)
```

Window `2097153` is wlroots' X11 proxy window, requesting from itself, and gets put into a transfer loop because those proxy windows aren't meant to never actually transfer anything.

I was pretty sure we reject self-transfers, so I'll have to go through that code more carefully tonight. The time difference between the two `XCB_XFIXES_SELECTION_NOTIFY` events is suspiciously small; this sounds like a race.

**Comment by mssdvd** [comment] 2021-02-10 15:58
> No problem, happy we got to the bottom of things. I imagine things would have reproduced with the primary selection if `wl-paste` was running on the primary selection rather than the clipboard.

Here is the script updated for testing the primary clipboard
```
include /etc/sway/config

exec {
    wl-paste -p -t text --watch clipman store
    echo "blaksdlsdkasdfdkjfhkajdfhjakdhfjkasdhfjasdbhjbrhasgfhdghfhjfhsdaj"|wl-copy -p
    # C-y prints the primary selection
    emacs -Q --eval="(global-set-key (kbd \"C-y\") #'(lambda () (interactive)(insert-for-yank (gui-get-primary-selection))))"
}
```

I don't think I ever used `wl-paste` with the primary selection flag so it probably doesn't matter much which clipboard `wl-paste` is watching , right?

**Comment by Xyene** [comment] 2021-02-11 02:12
Thanks that helped. Could you give https://github.com/swaywm/wlroots/pull/2739 a try?

**Comment by mssdvd** [comment] 2021-02-11 14:38
I've been using it for several hours and so far no problems at all.

**Comment by Xyene** [comment] 2021-02-13 05:39
Thanks for testing! I believe I've found the root cause and fixed it now. There were a stack of issues obscuring it, but they should be resolved now -- I wasn't comfortable on relying solely on the timestamps to determine if this race was happening, since they have very limited precision (and I'm pretty sure this was causing the contents being put into clipman to occasionally be wrong).

**Comment by mssdvd** [comment] 2021-02-13 07:06
Thanks for the hard work! Even to the untrained eye the solution seems much more robust.

**Closed** 2021-02-15 12:50 UTC
Labels: xwayland
