### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by Brane212** [swaywm/wlroots#2249] opened 2020-06-04 05:32 UTC
Build fails with:

```
In file included from ../include/wlr/backend.h:14,
                 from ../examples/tablet.c:10:
../include/wlr/render/egl.h:54:3: error: unknown type name ‘PFNEGLQUERYWAYLANDBUFFERWL’
   54 |   PFNEGLQUERYWAYLANDBUFFERWL eglQueryWaylandBufferWL;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
../include/wlr/render/egl.h:55:3: error: unknown type name ‘PFNEGLBINDWAYLANDDISPLAYWL’
   55 |   PFNEGLBINDWAYLANDDISPLAYWL eglBindWaylandDisplayWL;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
../include/wlr/render/egl.h:56:3: error: unknown type name ‘PFNEGLUNBINDWAYLANDDISPLAYWL’
   56 |   PFNEGLUNBINDWAYLANDDISPLAYWL eglUnbindWaylandDisplayWL;
```

**Comment by emersion** [comment] 2020-06-04 07:55
(Assuming you have Mesa + glvnd installed)

Yeah, this is caused by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4953

It'll be fixed once https://gitlab.freedesktop.org/glvnd/libglvnd/-/merge_requests/225 lands.

**Comment by Brane2** [comment] 2020-06-11 22:14
It looks like that patch is already in mesa-git, but wlroots bnuild still fails the same way.
BTW, last part of that patch fails against mesa-git, since file is relocated (egl.xml), but it looks like it was applied at its new location.

**Comment by myfreeweb** [comment] 2020-06-13 10:32
@Brane2 *libglvnd* needs to be patched to be compatible with mesa-git. the mesa-git patch is what *broke* the build.

**Comment by emersion** [comment] 2020-08-10 13:44
Closing because a libglvnd version has been released with the fix.

**Closed by emersion** 2020-08-10 13:44 UTC
