### ISSUE TITLE
axis_discrete events?

### ISSUE THREAD

**Issue by frank-bell** [swaywm/wlroots#2765] opened 2021-03-01 10:27 UTC
FreeRDP 2.3 recently switched to using axis_discrete events for scrolling, as prior implementations only scrolled a minimal amount. This has resulted in touchpad scrolling no longer working when connected to a remote machine via wlfreerdp (https://github.com/FreeRDP/FreeRDP/issues/6839#issuecomment-786644366). 

I see that #1628 is still a WIP, but just wanted to double-check that this is indeed still outstanding? That is, wlroots doesn't currently emit any axis_discrete events?

PS - I use Wayfire WM which is based on wlroots. I have checked their repo and there is no mention of axis_discrete at all, so assumed it is handled in wlroots.

**Comment by emersion** [comment] 2021-03-01 10:43
#1628 is not directly related to `axis_discrete`. wlroots should already emit `axis_discrete` events for input devices that provide it.

**Comment by frank-bell** [comment] 2021-03-01 11:14
Thanks for clarifying. It works remotely with mouse scroll wheel, but not via Apple Trackpad. All works as expected on local Wayland host.

Would debug logs show these `axis_discrete` events? I can then at least go back to FreeRDP with evidence.

**Comment by emersion** [comment] 2021-03-01 11:16
Note, you need to bind to a high enough `wl_seat` to get `axis_discrete` events.

It would be helpful to have some Wayland debug logs and some `libinput debug-events` logs.

**Comment by progandy** [comment] 2021-03-01 13:27
By the way, proper axis handling should probably cache the value in axis/axis_discrete and only choose the preferred operation during the wl_pointer_frame event.

https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_pointer
> *wl_pointer::frame - end of a pointer event sequence*
> Indicates the end of a set of events that logically belong together. A client is expected to accumulate the data in all events within the frame before proceeding.

**Comment by Xyene** [comment] 2021-03-01 14:15
wlroots only passes off what it received from libinput, and libinput touchpads don't have discrete axis events by design.

See https://wayland.freedesktop.org/libinput/doc/latest/api/group__event__pointer.html#ga38d12fc6884c9943e261febdb2384b98:

> If the source is LIBINPUT_POINTER_AXIS_SOURCE_WHEEL, the discrete value correspond to the number of physical mouse wheel clicks.
> 
> If the source is LIBINPUT_POINTER_AXIS_SOURCE_CONTINUOUS or LIBINPUT_POINTER_AXIS_SOURCE_FINGER, **the discrete value is always 0.**

(A touchpad is typically `LIBINPUT_POINTER_AXIS_SOURCE_FINGER`.)

**Comment by frank-bell** [comment] 2021-03-01 14:42
Thank you, will pass on the information.

**Comment by Xyene** [comment] 2021-03-02 02:03
I'm going to go ahead and close this issue here, and continue on the FreeRDP side if needed.

**Closed by Xyene** 2021-03-02 02:03 UTC

**Comment by ascent12** [comment] 2021-03-02 09:00
Yeah, just to clarify, axis_discrete basically only applies to the actual 'clicks' you get out of a mouse wheel. If you're using trackpad scrolling or have a "freewheeling mouse",  you shouldn't expect to get them.
