### ISSUE TITLE
Gamma control does not work

### ISSUE THREAD

**Issue by e00E** [swaywm/wlroots#1621] opened 2019-03-18 05:47 UTC
I was originally trying to use https://github.com/jonls/redshift/pull/704 but it does not work. There is no visible change in gamma or brightness but also no error message.

Then I tried wlroot's `gamma-control` example but I have the same problem for example with `./gamma-control -b 0.5`.

I am using the `sway-git` and `wlroots-git` arch linux aur packages `sway version 1.0-rc1-187-g0327c999 (Mar 18 2019, branch 'makepkg')`.

My graphics card is an `AMD RX Vega 64`. There is a single display connected via display port.

**Comment by emersion** [comment] 2019-03-18 05:50
Duplicate of https://github.com/swaywm/sway/issues/2700

**Closed by emersion** 2019-03-18 05:50 UTC
