### ISSUE TITLE
Windows change scaling on screen disable/renable

### ISSUE THREAD

**Issue by wucke13** [swaywm/wlroots#2221] opened 2020-05-25 13:49 UTC
When I switch the screen of my laptop on and off, (for example through `bindsym XF86Display output $laptop toggle` in sway), new windows spawn with approximately double scaled UI elements. The scaling looks crisp and everything. I can reproduce this on sway. On wayfire, it happens sometimes as well, but I did not figure out how to get it directly. Terefore I would guess this is a wlroots problem.

On the list of affected applications the following are:

+ Chromium
+ Firefox
+ Telegram Desktop

**Comment by emersion** [comment] 2020-05-25 13:50
Duplicate of https://github.com/swaywm/wlroots/issues/988

**Closed by emersion** 2020-05-25 13:50 UTC

**Comment by wucke13** [comment] 2020-05-25 14:16
Hmpf, thanks for the fast _fix_. Is there any chance that something happens on this? The upstream bug report seems to be not-so-active.

**Comment by emersion** [comment] 2020-05-25 14:17
> Is there any chance that something happens on this?

You're welcome to send a patch.

**Comment by wucke13** [comment] 2020-05-25 14:43
For my understanding: Is it the idiomatic thing to solve this upstream, in xwayland?

**Comment by emersion** [comment] 2020-05-25 14:44
Yes, this is an xwayland bug. Nothing we can do about it in wlroots.

**Comment by wucke13** [comment] 2020-05-25 14:54
Thank you!

**Comment by Emantor** [comment] 2020-05-26 04:42
Note that there is a workaround documented in the [Sway Wiki](https://github.com/swaywm/sway/wiki#after-unplugging-an-external-display-some-applications-appear-too-large-on-my-hidpi-screen)
