### ISSUE TITLE
Non-main GPUs not updating rendering.

### ISSUE THREAD

**Issue by JonathanILevi** [swaywm/wlroots#1329] opened 2018-10-24 01:16 UTC
I have a multiple GPU setting with 3 GPUs.

Only the monitors attached to the first GPU update what is rendering (the mouse excepted).   Switching ttys and back corrects the rending just once.  (If I open a window in one of the non-main GPU monitors nothing happens; switching ttys and back I see the new window but no new changes are applied until I switch ttys again.)

Regardless of the version of Sway:
commit `4e89a2` is the last commit that works.
commit `eb44d1` does not work (this commit reverts `1280b4`)
commit `1280b4` also does not work but `eb44d1` reverts it.

Using script to catch the terminal output I get:
```
Script started on 2018-10-23 20:03:49+00:00
[jonathan@j-dtop-arch ~]$ sway
i3status: trying to auto-detect output_format setting
i3status: auto-detected "i3bar"
2018-10-23 20:03:52 - ^[[1;31m[backend/drm/legacy.c:21] DVI-D-3: Failed to page flip: No such file or directory^[[0m
2018-10-23 20:03:52 - ^[[1;31m[backend/drm/legacy.c:21] DVI-I-1: Failed to page flip: No such file or directory^[[0m
Exiting due to signal.
[jonathan@j-dtop-arch ~]$ exit
exit

Script done on 2018-10-23 20:04:03+00:00
```

**Comment by emersion** [comment] 2018-10-24 06:44
Duplicate of 1328

**Closed by emersion** 2018-10-24 06:44 UTC
