### ISSUE TITLE
Eclipse (wayland) crashes sway

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/wlroots#2215] opened 2020-05-21 00:50 UTC
Browsing menus in Eclipse crashes Sway.
`sway version 1.4-45e4e921 (May 20 2020, branch 'master')`
[gdb.txt](https://github.com/swaywm/wlroots/files/4660048/gdb.txt)
[sway.log](https://github.com/swaywm/wlroots/files/4660049/sway.log)

**Comment by Xyene** [comment] 2020-05-21 00:54
This is a duplicate of  https://github.com/swaywm/sway/issues/5294, introduced in https://github.com/swaywm/sway/commit/091f580b7cb0df92f0f6e0be34b52f8abfdbe97a (you can follow the linked issues for some more context and discussion, if you're interested).

**Closed by Xyene** 2020-05-21 00:54 UTC

**Comment by JonnyMako** [comment] 2020-05-21 01:34
ok, thanks. I guess this is the PR I should wait for the merge to happen?
