### ISSUE TITLE
Tinywl stucks when staring from TTY

### ISSUE THREAD

**Issue by AlynxZhou** [swaywm/wlroots#2079] opened 2020-03-23 07:47 UTC
I'm creating my own compositor with wlroots, and I failed to start it under TTY, it just make my computer freeze and I need to restart, I also tried tinywl and I got the same result.

I have systemd in my computer, and I really want to know how to make a compositor with systemd-logind, is there anything I need to do with wlroots?

**Comment by ascent12** [comment] 2020-03-23 08:47
Can you post a debug log?

**Comment by emersion** [comment] 2020-03-23 08:57
Duplicate of https://github.com/swaywm/wlroots/issues/2075

**Closed by emersion** 2020-03-23 08:57 UTC

**Comment by AlynxZhou** [comment] 2020-03-23 09:01
> Can you post a debug log?

Sorry, but I am not posting a bug, I want to ask some questions (because there's no doc about this), I've created a compositor, and I do rendering by handling the `wlr_output::frame` event just like tinywl, but when I am running it in TTY, no `wlr_output::frame` was triggered, the output just freeze.

If there is no `wlr_output::frame` when running in TTY (DRM backend), how can I do frame rendering? I want to get some info about this. Thanks!

PS When I submit this issue I think freeze is because of DRM backend not starting, but I managed to stop my compositor and find it works but just no frame rendered.

**Comment by ammen99** [comment] 2020-03-23 11:03
@AlynxZhou, I do not think there is documentation, I would recommend comparing your compositor to tinywl and see what is different. You could also start with tinywl's code and modify it so that it does what you want it to.

**Comment by artsi0m** [comment] 2020-03-23 20:03
> Can you post a debug log?

Here tinywl debug log:
https://gist.github.com/artsi0m/ca898b6b596ab15ada482110cb3f2a03

**Comment by AlynxZhou** [comment] 2020-03-24 01:42
> @AlynxZhou, I do not think there is documentation, I would recommend comparing your compositor to tinywl and see what is different. You could also start with tinywl's code and modify it so that it does what you want it to.

Hi, I'm already starting it by modifying tinywl, and both of them leave me a frozen TTY, I am still finding reasons...

**Comment by AlynxZhou** [comment] 2020-03-24 01:46
Here's my compositor's debug log:
https://gist.github.com/AlynxZhou/dcff0f4f8e73800d90fceda7dd085e2d

**Comment by AlynxZhou** [comment] 2020-03-27 02:30
Hi, is there any updates?
