### ISSUE TITLE
Use EGL device extensions

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#1491] opened 2019-01-23 06:01 UTC
Recently mesa added support for various EGL device related extensions: https://www.mesa3d.org/relnotes/18.3.0.html
These may end up being relevant to us.

**Comment by emersion** [comment] 2019-01-23 07:41
I've looked into this, but I don't think this will be useful. It seems like a DRM abstraction.

**Comment by ascent12** [comment] 2019-01-23 07:47
>It seems like a DRM abstraction

That's the other part of it, which is probably only implemented by the Nvidia driver and we wouldn't give a shit about.

Mesa is using some of the device enumeration stuff to explicitly select what device the context is created with, and is related to this XDC talk: https://www.youtube.com/watch?v=9WOgihsCKAA
It may not end up being relevant to us with the new renderer design where we're using GBM, but I'm not entirely sure yet. It also allows us to explicitly pick a software-based EGL context.

**Comment by emersion** [comment] 2019-01-23 07:56
> Mesa is using some of the device enumeration stuff to explicitly select what device the context is created with

Oh right, I see. Yeah, I'm not sure what happens with `EGL_PLATFORM_GBM_MESA`, since we already provide the GBM device. I don't think this can work for software-based rendering.

**Comment by emersion** [comment] 2021-06-24 11:19
Duplicate of https://github.com/swaywm/wlroots/issues/2649

**Closed by emersion** 2021-06-24 11:19 UTC
Labels: renderer
