### ISSUE TITLE
libseat: Unable to create seat: Function not implemented

### ISSUE THREAD

**Issue by muevoid** [swaywm/wlroots#2400] opened 2020-09-11 18:46 UTC
I am using seatd backend for libseat on master wlroots and sway. However when trying to start sway I get the following errors:

```
backend/sessions/libseat.c:102 Unable to create seat: Function not implemented
```

I am on KISS linux(musl libc)

**Comment by emersion** [comment] 2020-09-11 18:49
cc @kennylevinsen

**Comment by kennylevinsen** [comment] 2020-09-11 20:42
> ```
> backend/sessions/libseat.c:102 Unable to create seat: Function not implemented
> ```

ENOSYS is returned if no backend succeeds.

Which backend are you trying to use? seatd? If so, did you specify a group for the seatd socket that you are a member of?

**Comment by emersion** [comment] 2020-09-11 20:44
Can you obtain debug logs, @muevoid?

**Comment by muevoid** [comment] 2020-09-11 20:47
@kennylevinsen I did not specify a group. Do I just create a new group add myself to it and give seatd that parameter?

**Comment by kennylevinsen** [comment] 2020-09-11 20:50
> @kennylevinsen I did not specify a group. Do I just create a new group add myself to it and give seatd that parameter?
> 
> Edit: yes I am using the seatd backend.

Yes (or use something like `video` if you prefer).

> Can you obtain debug logs, @muevoid?

We should do the subsystem log level configuration...

**Comment by muevoid** [comment] 2020-09-11 20:54
Using video as the group worked perfectly, thank you!

**Comment by kennylevinsen** [comment] 2020-09-13 10:32
@muevoid Please close the issue if the problem is fixed. :)

**Closed** 2020-09-13 10:32 UTC
