### ISSUE TITLE
wlroots 0.14.0 mouse pointer invisible on external displays with multi-GPU

### ISSUE THREAD

**Issue by nwg-piotr** [swaywm/wlroots#2995] opened 2021-06-29 16:42 UTC
I'm on a full-AMD laptop with Ryzen 7 3750H and Radeon Pro 5500M + Radeon Vega 10. External displays work with the discrete card. Since today's wlroots update on Arch Linux I no longer see the mouse pointer on external displays.

**Comment by emersion** [comment] 2021-06-29 16:43
Duplicate of https://github.com/swaywm/sway/issues/6351

**Comment by emersion** [comment] 2021-07-05 09:09
Can you try https://github.com/swaywm/wlroots/pull/3021?

**Comment by emersion** [comment] 2021-07-05 21:35
Also, can you collect a debug log?

**Comment by nwg-piotr** [comment] 2021-07-05 22:56
I'm afraid it doesn't help.

Log: https://gist.github.com/nwg-piotr/7746ae34c5111a97e996a7ded5fa3e2a

**Comment by emersion** [comment] 2021-07-05 23:40
Closing as a duplicate, confirmed this is the same bug.

**Closed by emersion** 2021-07-05 23:40 UTC
Labels: backend/drm, bug

**Comment by nwg-piotr** [comment] 2021-07-05 23:42
Yes, @IntinteDAO and I use the very same hardware.
