### ISSUE TITLE
Sway 1.6 (wlroots 0.13) update doesn't launch

### ISSUE THREAD

**Issue by notramo** [swaywm/wlroots#2917] opened 2021-05-06 19:51 UTC
I had a working Sway installation. v1.5 worked fine, but when I start v1.6 from console with the `sway` command, it doesn't launch.
The console completely freezes. I can't terminate Sway with Ctrl+C, but it responds to the configured exit keybinding, and ends the session. After it exited, the console is updated, and an error message (attached below) becomes visible. The console output of autostarted applications also becomes visible.
Xorg and i3 works properly.
```
00:00:00.127 [wlr] [backend/headless/backend.c:142] Renderer doesn't support XRGB8888
00:00:00.495 [wlr] [backend/drm/renderer.c:236] Renderer doesn't support format 0x34325258
00:00:00.495 [wlr] [backend/drm/renderer.c:236] Renderer doesn't support format 0x34325258
00:00:00.495 [wlr] [backend/drm/drm.c:785] connector LVDS-1: Failed to initialize renderer for plane
00:00:00.495 [sway/config/output.c:417] Failed to commit output LVDS-1
00:00:00.495 [wlr] [backend/drm/renderer.c:236] Renderer doesn't support format 0x34325258
00:00:00.495 [wlr] [backend/drm/renderer.c:236] Renderer doesn't support format 0x34325258
```

**Comment by emersion** [comment] 2021-05-07 09:24
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by milisarge** [comment] 2021-05-07 13:08
i have similar issue with wlroots 0.13.0 on Qemu/KVM default VGA, i tested it with sway and wayfire. here is some logs:

device info : https://0x0.st/-BQA.txt
dmes.log for drm : https://0x0.st/-BQb.log
wayfire debug log: https://0x0.st/-BQc.txt
sway debug log: https://0x0.st/-BQW.txt

**Comment by notramo** [comment] 2021-05-08 13:51
@emersion There is the debug log: https://gist.github.com/notramo/96d60e37b8161b84aafa1ed42bca31ba

**Comment by emersion** [comment] 2021-05-10 08:54
Duplicate of https://github.com/swaywm/wlroots/issues/2506

**Closed by emersion** 2021-05-10 08:54 UTC
