### ISSUE TITLE
Sway fails to start

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/wlroots#2854] opened 2021-04-14 13:23 UTC
Starting with https://github.com/swaywm/wlroots/commit/d50bbf0bbc49a9a8e010668cd357aba968ae884b

Sway fails to start.

```
00:00:01.219 [DEBUG] [sway/server.c:218] Initializing Xwayland (lazy=1)
00:00:01.219 [INFO] [sway/server.c:241] Starting backend on wayland display 'wayland-1'
00:00:01.219 [DEBUG] [wlr] [backend/libinput/backend.c:86] Initializing libinput
00:00:01.227 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event2: Permission denied
00:00:01.227 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event4: Permission denied
00:00:01.227 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event3: Permission denied
00:00:01.228 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event1: Permission denied
00:00:01.228 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event0: Permission denied
00:00:01.228 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event9: Permission denied
00:00:01.228 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event27: Permission denied
00:00:01.228 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event28: Permission denied
00:00:01.228 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event29: Permission denied
00:00:01.228 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event30: Permission denied
00:00:01.228 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event31: Permission denied
00:00:01.229 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event14: Permission denied
00:00:01.229 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event15: Permission denied
00:00:01.229 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event19: Permission denied
00:00:01.229 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event20: Permission denied
00:00:01.229 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event8: Permission denied
00:00:01.230 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event10: Permission denied
00:00:01.230 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event11: Permission denied
00:00:01.230 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event12: Permission denied
00:00:01.230 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event13: Permission denied
00:00:01.230 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event16: Permission denied
00:00:01.231 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event17: Permission denied
00:00:01.231 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event18: Permission denied
00:00:01.231 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event21: Permission denied
00:00:01.231 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event22: Permission denied
00:00:01.231 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event23: Permission denied
00:00:01.231 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event24: Permission denied
00:00:01.232 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event25: Permission denied
00:00:01.232 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event257: Permission denied
00:00:01.232 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event256: Permission denied
00:00:01.232 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event260: Permission denied
00:00:01.232 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event5: Permission denied
00:00:01.233 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event258: Permission denied
00:00:01.233 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event261: Permission denied
00:00:01.233 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event259: Permission denied
00:00:01.233 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event7: Permission denied
00:00:01.233 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event26: Permission denied
00:00:01.233 [ERROR] [wlr] [backend/session/direct.c:49] Failed to open /dev/input/event6: Permission denied
00:00:01.233 [ERROR] [wlr] [backend/libinput/backend.c:115] libinput initialization failed, no input devices
00:00:01.234 [ERROR] [wlr] [backend/libinput/backend.c:116] Set WLR_LIBINPUT_NO_DEVICES=1 to suppress this check
00:00:01.234 [ERROR] [wlr] [backend/multi/backend.c:33] Failed to initialize backend.
00:00:01.234 [ERROR] [sway/server.c:244] Failed to start backend
00:00:01.290 [INFO] [sway/main.c:436] Shutting down sway
```

**Comment by emersion** [comment] 2021-04-14 13:34
Duplicate of https://github.com/swaywm/sway/issues/6179.

**Closed by emersion** 2021-04-14 13:34 UTC
