### ISSUE TITLE
Failed to create drm backend in sway 1.6

### ISSUE THREAD

**Issue by pan1997** [swaywm/wlroots#2869] opened 2021-04-18 09:28 UTC
Running nouveau drivers on arch. Sway 1.5.1 ran on this setup, but after update, sway 1.6 fails to start. Attached the error log.

```
00:00:00.050 [ERROR] [wlr] [EGL] command: eglGetPlatformDisplay, error: EGL_BAD_PARAMETER (0x300c), message: "EGL_BAD_PARAMETER error: In internal function: Additional INFO may be available
"
00:00:00.741 [ERROR] [wlr] [EGL] command: eglQueryDevicesEXT, error: EGL_BAD_ALLOC (0x3003), message: "EGL_BAD_ALLOC error: In eglQueryDevicesEXT: Failed to allocate device list.
"
00:00:00.741 [ERROR] [wlr] [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_DISPLAY (0x3008), message: "(null)"
00:00:00.741 [ERROR] [wlr] [render/egl.c:280] eglQueryDeviceStringEXT(EGL_EXTENSIONS) failed
00:00:00.741 [ERROR] [wlr] [EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "Invalid display (nil)"
00:00:00.742 [ERROR] [wlr] [render/wlr_renderer.c:263] Could not initialize EGL
00:00:00.743 [ERROR] [wlr] [backend/drm/renderer.c:34] Failed to create EGL/WLR renderer
00:00:00.744 [ERROR] [wlr] [backend/drm/backend.c:201] Failed to initialize renderer
00:00:00.744 [ERROR] [wlr] [backend/backend.c:174] Failed to create DRM backend
00:00:00.755 [ERROR] [wlr] [EGL] command: eglGetPlatformDisplay, error: EGL_BAD_PARAMETER (0x300c), message: "EGL_BAD_PARAMETER error: In internal function: Additional INFO may be available
"
00:00:00.756 [ERROR] [wlr] [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_DISPLAY (0x3008), message: "(null)"
00:00:00.756 [ERROR] [wlr] [render/egl.c:280] eglQueryDeviceStringEXT(EGL_EXTENSIONS) failed
00:00:00.756 [ERROR] [wlr] [EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "Invalid display (nil)"
00:00:00.756 [ERROR] [wlr] [render/wlr_renderer.c:263] Could not initialize EGL
00:00:00.756 [ERROR] [wlr] [backend/drm/renderer.c:34] Failed to create EGL/WLR renderer
00:00:00.803 [ERROR] [wlr] [backend/drm/backend.c:201] Failed to initialize renderer
00:00:00.804 [ERROR] [wlr] [backend/backend.c:174] Failed to create DRM backend
00:00:00.804 [ERROR] [wlr] [backend/backend.c:312] Failed to open any DRM device
00:00:00.851 [ERROR] [sway/server.c:55] Unable to create backend
```

**Comment by Porcupine96** [comment] 2021-04-18 09:36
I've run into the same issue (see the discussion [Reddit](https://www.reddit.com/r/swaywm/comments/mt2tt3/sway_does_not_start_after_upgrade_to_16/)).

The difference is that I don't use nouveau drivers (nor any other for that matter). 

Upgrading libglvnd to upstream (libglvnd-git) makes it work but in my case it causes a flickering issue described in [to be linked in a sencond].

**Comment by ouchadam** [comment] 2021-04-18 09:37
with `libglvnd-git` I'm able to launch sway however it's unusable 

![IMG_20210418_103057](https://user-images.githubusercontent.com/1848238/115140989-fa69a000-a031-11eb-8768-22b5b95547be.jpg)

**Comment by RPigott** [comment] 2021-04-18 10:52
The EGL_BAD_PARAMETER is a dupe of #2480, you need to upgrade libglvnd.

The rendering issues are something else. You should open different issues for that.

**Closed by RPigott** 2021-04-18 10:52 UTC
