### ISSUE TITLE
"Atomic commit failed (modeset): Invalid argument" when connecting third display

### ISSUE THREAD

**Issue by luispabon** [swaywm/wlroots#2095] opened 2020-04-02 10:06 UTC
I have a Dell XPS 9560, intel graphics and a thunderbolt dock with hdmi and vga outs. I have one display connected on each port, as well as the laptop's eDP display ([outputs](https://gist.github.com/luispabon/8ee0fd19babb1040c03ecd14c731f9b3)).

Whenever I connect in the thunderbolt dock, only one of the external displays will come up online. The other one appears as "inactive". When I manually try to turn it on via `swaymsg "output DP-8 dpms on"` the following appears on sways' logs and the display remains off:

```
2020-04-02 11:04:48 - [backend/drm/atomic.c:56] DP-8: Atomic commit failed (modeset): Invalid argument
2020-04-02 11:04:48 - [backend/drm/atomic.c:56] DP-8: Atomic commit failed (modeset): Invalid argument
2020-04-02 11:04:48 - [backend/drm/atomic.c:56] DP-8: Atomic commit failed (modeset): Invalid argument
2020-04-02 11:04:48 - [backend/drm/drm.c:636] Failed to initialize renderer on connector 'DP-8': initial page-flip failed
2020-04-02 11:04:48 - [backend/drm/drm.c:719] Failed to initialize renderer for plane
2020-04-02 11:04:48 - [sway/config/output.c:401] Failed to modeset output DP-8
```

Sway 1.4
wlroots 0.10.1
Ubuntu 20.04

**Comment by emersion** [comment] 2020-04-02 10:07
Duplicate of https://github.com/swaywm/wlroots/issues/1877

**Closed by emersion** 2020-04-02 10:08 UTC

**Comment by luispabon** [comment] 2020-04-02 10:11
Thank you :+1:
