### ISSUE TITLE
Failed to initialize renderer

### ISSUE THREAD

**Issue by yellowhat** [swaywm/wlroots#2965] opened 2021-06-13 11:38 UTC
Hi,
I am using sway on Fedora 34, unfortunatelly, in the last month, I am getting the following error:

```
00:00:00.735 [ERROR] [wlr] [backend/drm/atomic.c:35] connector DP-1: Atomic commit failed (modeset): Invalid argument
00:00:00.735 [INFO] [wlr] [backend/drm/drm.c:701] connector DP-1: Page-flip failed with primary FB modifiers enabled, retrying without modifiers
00:00:00.735 [DEBUG] [wlr] [render/swapchain.c:105] Allocating new swapchain buffer
00:00:00.740 [DEBUG] [wlr] [render/gbm_allocator.c:123] Allocated 3840x2160 GBM buffer (format 0x34325241, modifier 0xFFFFFFFFFFFFFF)
00:00:00.740 [DEBUG] [wlr] [render/gles2/renderer.c:131] Created GL FBO for buffer 3840x2160
00:00:00.740 [ERROR] [wlr] [backend/drm/atomic.c:35] connector DP-1: Atomic commit failed (modeset): Invalid argument
00:00:00.740 [ERROR] [wlr] [backend/drm/drm.c:715] connector DP-1: Failed to initialize renderer:initial page-flip failed
00:00:00.740 [ERROR] [wlr] [backend/drm/drm.c:785] connector DP-1: Failed to initialize renderer for plane
00:00:00.740 [ERROR] [sway/config/output.c:417] Failed to commit output DP-1
```

This is the `sway -d` output: [sway.log](https://github.com/swaywm/wlroots/files/6643802/sway.log), using sway 1.6 and wlroots 0.13.0.

As you can see I have 2 monitors attached to my laptop and only 1 is working at the moment, the other one `eDP-1` is frozen at the tty.

I am getting the same behavior using sway and wlroots from git.

Unfortunatelly, as I usually use the git version, I though that there was something wrong upstream and did not pay much attention; but even after downgrading to the official Fedora release I get the same behavior.

Is this something releated to mesa? 

Thanks

**Comment by emersion** [comment] 2021-06-13 11:42
Can you obtain DRM debug logs? See https://github.com/swaywm/wlroots/wiki/DRM-Debugging

**Comment by yellowhat** [comment] 2021-06-13 11:50
Sure:
[dmesg.log](https://github.com/swaywm/wlroots/files/6643819/dmesg.log)

**Comment by emersion** [comment] 2021-06-13 11:51
```
[ 1115.383533] i915 0000:00:02.0: [drm:skl_compute_wm [i915]] Requested display configuration exceeds system DDB limitations
[ 1115.383562] i915 0000:00:02.0: [drm:skl_compute_wm [i915]] minimum required 242/199
```

Can you try `WLR_DRM_NO_MODIFIERS=1`?

**Comment by yellowhat** [comment] 2021-06-13 11:56
Exporting that flag did the trick.
May I ask what may have changed in my system that triggered this?

Thanks

**Comment by emersion** [comment] 2021-06-13 11:57
Maybe a new kernel? Not sure.

Closing as a duplicate of https://github.com/swaywm/wlroots/issues/1873.

**Closed by emersion** 2021-06-13 11:57 UTC
