### ISSUE TITLE
Fail to create backend with current master

### ISSUE THREAD

**Issue by Boudin** [swaywm/wlroots#2797] opened 2021-03-20 11:57 UTC
OS : Arch
Mesa: 20.3.4
GPU: AMD Radeon 7850
wlroots: master (commit c740fccc9dd0913908c0632c10f8c6d10b2b1ca4)
sway: master (6271bd06e940d1ef289804f9ea2a1e1bf65af559)

I have no issue running sway 1.5.1 with wlroots 0.12 or others wlroots based compositors like river and wayfire.
But, with the current wlroots master, sway fails to start. River and wayfire also fails, with the same error:
```
00:00:00.062 [ERROR] [wlr] [render/wlr_renderer.c:263] Could not initialize EGL
00:00:00.062 [ERROR] [wlr] [backend/drm/renderer.c:33] Failed to create EGL/WLR renderer
00:00:00.063 [ERROR] [wlr] [backend/drm/backend.c:201] Failed to initialize renderer
00:00:00.064 [ERROR] [wlr] [backend/backend.c:174] Failed to create DRM backend
00:00:00.064 [ERROR] [wlr] [backend/backend.c:312] Failed to open any DRM device
``` 

Here's the logs with sway and wlroots master:
[dmesg_master.log](https://github.com/swaywm/wlroots/files/6175465/dmesg_master.log)
[sway_master.log](https://github.com/swaywm/wlroots/files/6175466/sway_master.log)

Here's the logs with sway 1.5.1 and wlroots 0.12
[dmesg_15.log](https://github.com/swaywm/wlroots/files/6175467/dmesg_15.log)
[sway_15.log](https://github.com/swaywm/wlroots/files/6175468/sway_15.log)

**Comment by emersion** [comment] 2021-03-22 13:59
Duplicate of https://github.com/swaywm/wlroots/issues/2480

**Closed by emersion** 2021-03-22 13:59 UTC
