### ISSUE TITLE
Hardware cursor persists when switching to KMSCON on another tty

### ISSUE THREAD

**Issue by ericonr** [swaywm/wlroots#1952] opened 2019-12-18 19:13 UTC
sway version 1.2-452a615b (Dec 16 2019, branch 'master')
Mesa 19.2.7, i915 driver

When using sway and switching to another tty that's specifically running KMSCON (GPU accelerated framebuffer implementation), the mouse cursor is still in the KMSCON screen, and stays there forever. If I switch to a usual tty screen running getty, the cursor disappears and doesn't reappear as long as I don't switch back to sway.

I am unsure whether this is a sway or graphics bug, so would gladly report this elsewhere if told to.

**Comment by emersion** [comment] 2019-12-18 19:25
wlroots should cleanup the KMS state before TTY switch.

**Comment by ericonr** [comment] 2019-12-19 00:19
I hadn't thought it could be due to wlroots. I will give it a try with Wayfire as well, then.

**Comment by ascent12** [comment] 2019-12-19 08:48
>wlroots should cleanup the KMS state before TTY switch.

By the time a TTY switch happens, it's possible that we're already lost DRM master privileges and can't do anything about it.

**Comment by emersion** [comment] 2019-12-19 09:19
If we handle the switch ourselves it's fine (e.g. Ctrl+Alt+Fn). See https://blog.ffwll.ch/2016/01/vt-switching-with-atomic-modeset.html

**Comment by ericonr** [comment] 2019-12-20 07:48
Have you been able to reproduce this? I've found that both Wayfire and Plasma Wayland (which doesn't use wlroots) had the same issue in my machine.

> See https://blog.ffwll.ch/2016/01/vt-switching-with-atomic-modeset.html

The solution that it guarantees should always work is indeed what worked for me, going to a normal tty screen with getty.

**Comment by emersion** [comment] 2020-12-23 11:32
Closing as a duplicate of https://github.com/swaywm/wlroots/issues/2160

**Closed by emersion** 2020-12-23 11:32 UTC
Labels: backend/drm
