### ISSUE TITLE
Xwayland scaling issue

### ISSUE THREAD

**Issue by HoshiYamazaki** [swaywm/wlroots#1633] opened 2019-03-22 22:03 UTC
I want to ask, can we scale window, for example Wine with custom resolution turned on (virtual desktop) to match full resolution on monitor?
For now if window is bigger, it overflows the border, if its smaller, just content under border is smaller and there are graphical artifacts.
Also is it possible for example - I have setup with FullHD screen and 4K, I use 2 * scaling on 4K. If we turn Wine app with 2560x1440 res under scaled monitor under xwayland to not lose quality and display it not in 1920x1080 (like it's scaled from 4K) but under 2560x1440, just matching fullscreen mode?
Thanks and I wish you good night :) I appreciate your work on Sway.

**Comment by PanAeon** [comment] 2020-04-27 03:36
Is this one duplicate of https://github.com/swaywm/wlroots/issues/1635 ?

**Comment by HoshiYamazaki** [comment] 2020-04-28 09:02
If I remember correctly, it is, but with one addition - Windows 10 can scale apps based on display scaling settings (100-200%), and I assume Sway could do the same, based on multiplier in the config.

**Comment by emersion** [comment] 2020-04-28 09:04
>I assume Sway could do the same, based on multiplier in the config

No, this isn't possible for Xwayland.

**Closed by emersion** 2020-04-28 09:04 UTC
